-- Path: src/lib/migrations/000_add-items-table.sql
-- This file was automatically generated by scripts/create-migration.ts

CREATE TABLE IF NOT EXISTS `items` (
	id SERIAL PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
